site_name: {{ cookiecutter.workspace_name }}
site_description: {{ cookiecutter.workspace_description }}
repo_url: {{ cookiecutter.__repo_url }}

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: { icon: material/weather-night, name: Dark mode }
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: { icon: material/weather-sunny, name: Light mode }

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
